openapi: 3.1.0
info:
  version: 1.0.0
  title: 'Goit'
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: 'GoIt'
tags:
  - name: Contacts

servers:
  - url: http://localhost:3000
  - url: https://nodejs-hw-mongodb-5-wwd3.onrender.com
paths:
  /contacts:
    post:
      $ref: ../swagger/paths/contacts/post.yaml
    get:
      $ref: ../swagger/paths/contacts/get.yaml
  /contacts/{contactId}:
    get:
      $ref: ../swagger/paths/contacts/contactId/get.yaml
    patch:
      $ref: ../swagger/paths/contacts/patch.yaml
    delete:
      $ref: ../swagger/paths/contacts/delete.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
