openapi: 3.1.0
info:
  version: 1.0.0
  title: 'Goit'
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: 'GoIt'
tags:
  - name: Contacts

servers:
  - url: http://localhost:3000
  - url: #посилання на задеплоєний сайт
paths:
  /contacts/{id}:
    get:
      $ref: ../swagger/paths/contacts/{id}/get.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
